/**
 * Model used to GET and POST Holes.
 * Hole will not have an ID if being posted, ID will be generated by the server
 */


export interface Hole {
    par: number;
    shots: number;
    hole_number: number;
    id?: number;
}