/**
 * Model used to GET and POST Holes.
 * A Hole will not have an ID if being posted; the ID will be generated by the server.
 * 
 * @property {number} par - The par value of the Hole.
 * @property {number} shots - The number of shots taken on the Hole.
 * @property {number} hole_number - The number of the Hole in the Round.
 * @property {number} [id] - ID of the Hole, automatically generated by the database so not needed for POST.
 */
export interface Hole {
    /** The par value of the Hole */
    par: number;
    /** The number of shots taken on the Hole */
    shots: number;
    /** The number of the Hole in the Round */
    hole_number: number;
    /** ID of the Hole, automatically generated by the database so not needed for POST  */
    id?: number;
}
