import { Round } from "./round.model";
/**
 * Model used to GET and POST Players.
 * A Player does not need to have any Rounds.
 * If the Player is being POSTed, it will not have an ID.
 * 
 * @property {string} name - The name of the Player.
 * @property {number} [id] - ID of the Player, automatically generated by the database so not needed for POST.
 * @property {Round[]} [rounds] - An optional array of Rounds played by the Player.
 */
export interface Player {
    /** The name of the Player */
    name: string;
    /** ID of the Player, automatically generated by the database so not needed for POST */
    id?: number;
    /** An optional array of Rounds played by the Player */
    rounds?: Round[];
}
