import { Hole } from "./hole.model";

/**
 * Model used to GET a Round.
 * This model is used as the return type of a Round for a specific Player,
 * not for the top rounds list.
 * 
 * @property {number} [id] - ID of the Player, automatically generated by the database so not needed for POST.
 * @property {Hole[]} holes - An array of Hole objects representing each hole played in the Round.
 */
export interface Round {
    /** ID of the Player, automatically generated by the database so not needed for POST */
    id?: number;
    /** An array of Hole objects representing each hole played in the Round */
    holes: Hole[];
}
